# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-12 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181209_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=0, verbose_name='轮播顺序'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/', verbose_name='轮播图'),
        ),
    ]
