# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-26 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181209_1706'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0003_auto_20181226_1148'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set([('user', 'goods')]),
        ),
    ]
